name: ridy
description: Rider Application of Taxi

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.5.9+166

environment:
  sdk: ^3.0.2
  flutter: ^3.10.2

dependencies:
  country_code_picker: ^3.0.0
  country_codes: ^2.2.0
  dots_indicator: ^3.0.0
  dotted_line: ^3.2.2
  equatable: ^2.0.3
  # facebook_app_events: 0.19.0
  file_picker: ^5.3.3
  firebase_analytics: 10.4.4
  firebase_app_check: ^0.1.5+1
  firebase_auth: 4.7.1
  firebase_core: 2.15.1
  firebase_crashlytics: 3.3.4
  firebase_messaging: 14.6.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_map: ^5.0.0
  flutter_map_animations: ^0.4.1
  flutter_map_location_marker: ^7.0.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  json_annotation: ^4.5.0
  latlong2: ^0.9.0
  lifecycle: ^0.7.0
  meta: ^1.3.0
  modal_bottom_sheet: 3.0.0-pre
  package_info_plus: ^4.0.2
  pinput: ^2.3.0
  share_plus: ^7.0.2
  shimmer: ^3.0.0
  timeago_flutter: ^3.4.0
  url_launcher: ^6.1.12
  client_shared:
    path: ../../libs/client-shared

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  graphql_codegen: 0.13.5
  # flutter_test:
  #   sdk: flutter

dependency_overrides:
  modal_bottom_sheet: 3.0.0-pre
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - google_fonts/
    - ionicons/

flutter_intl:
  enabled: true

flutter_gen:
  integrations:
    flutter_svg: true
