name: ridy
description: Driver application of Ridy

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.5.7+165

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: 1.17.1
  country_code_picker: ^3.0.0
  country_codes: ^2.2.0
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_analytics: 10.4.4
  firebase_app_check: ^0.1.5+1
  firebase_auth: 4.7.1
  firebase_core: 2.15.1
  firebase_crashlytics: 3.3.4
  firebase_messaging: 14.6.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_map: ^5.0.0
  flutter_map_animations: ^0.4.1
  flutter_map_location_marker: ^7.0.2
  flutter_svg: ^2.0.7
  flutter_vector_icons: ^2.0.0
  geolocator: ^9.0.2
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  graphql_flutter: ^5.2.0-beta.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.0.0
  intl: ^0.18.0
  json_annotation: ">=4.8.0"
  latlong2: ^0.9.0
  lifecycle: ^0.7.0
  map_launcher: ^2.5.0+1
  meta: ^1.3.0
  modal_bottom_sheet: 3.0.0-pre
  package_info_plus: ^4.0.2
  pinput: ^2.3.0
  shimmer: ^3.0.0
  timeago_flutter: ^3.5.0
  url_launcher: ^6.1.12
  client_shared:
    path: ../../libs/client-shared
  flutter_ringtone_player: ^3.2.0
  maps_toolkit: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.2.0
  graphql_codegen: 0.13.5

dependency_overrides:
  modal_bottom_sheet: 3.0.0-pre
  http: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - ionicons/
    - google_fonts/

flutter_intl:
  enabled: true

flutter_gen:
  integrations:
    flutter_svg: true
